version: '3.9'

services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: workout_db
      POSTGRES_USER: workout_user
      POSTGRES_PASSWORD: workout_pass
    ports:
      - "5432:5432"

  web:
    build: .
    command: gunicorn workout_project.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DEBUG: "False"
      DJANGO_SECRET_KEY: "your-secret-key"
      DJANGO_ALLOWED_HOSTS: "*"
      DB_NAME: workout_db
      DB_USER: workout_user
      DB_PASSWORD: workout_pass
      DB_HOST: db
      DB_PORT: 5432

volumes:
  postgres_data:

