# Generated by Django 5.2.6 on 2025-09-30 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Muscle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('group', models.CharField(choices=[('chest', 'Chest'), ('back', 'Back'), ('shoulders', 'Shoulders'), ('arms', 'Arms'), ('core', 'Core'), ('legs', 'Legs'), ('glutes', 'Glutes'), ('full_body', 'Full Body')], help_text='General muscle group this muscle belongs to', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Optional description of this muscle')),
                ('origin', models.CharField(blank=True, help_text='Origin point of the muscle', max_length=100, null=True)),
                ('insertion', models.CharField(blank=True, help_text='Insertion point of the muscle', max_length=100, null=True)),
                ('function', models.TextField(blank=True, help_text='Primary function of the muscle', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(help_text='General description of the exercise')),
                ('instructions', models.TextField(help_text='Step-by-step guide to perform the exercise')),
                ('equipment', models.CharField(blank=True, help_text='Equipment required, if any', max_length=100, null=True)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('exercise_type', models.CharField(choices=[('strength', 'Strength'), ('cardio', 'Cardio'), ('flexibility', 'Flexibility'), ('endurance', 'Endurance')], default='strength', max_length=20)),
                ('calories_burned', models.PositiveIntegerField(blank=True, help_text='Estimated calories burned per session', null=True)),
                ('duration', models.PositiveIntegerField(blank=True, help_text='Typical duration in seconds', null=True)),
                ('tips', models.TextField(blank=True, help_text='Additional tips or safety notes', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_muscles', models.ManyToManyField(help_text='Muscles primarily targeted by this exercise', related_name='exercises', to='exercises.muscle')),
            ],
        ),
    ]
