# Generated by Django 5.2.6 on 2025-10-02 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout_plan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(help_text='Week number in the plan (e.g., 1, 2, 3, 4)', verbose_name='Order')),
                ('notes', models.TextField(blank=True, help_text='Optional notes for this week', verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workout_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weeks', to='workout_plan.workoutplan', verbose_name='Workout Plan')),
            ],
            options={
                'verbose_name': 'Workout Week',
                'verbose_name_plural': 'Workout Weeks',
                'ordering': ['order'],
                'unique_together': {('workout_plan', 'order')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='workoutday',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='workoutday',
            name='workout_week',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='days', to='workout_plan.workoutweek', verbose_name='Workout Week'),
        ),
        migrations.AlterUniqueTogether(
            name='workoutday',
            unique_together={('workout_week', 'day_of_week')},
        ),
        migrations.RemoveField(
            model_name='workoutday',
            name='workout_plan',
        ),
    ]
