# Generated by Django 5.2.6 on 2025-09-30 23:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exercises', '0001_initial'),
        ('workout_plan', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(help_text="E.g., 'Bench pressed 100kg for 5 reps'", max_length=255)),
                ('value', models.CharField(help_text='E.g., 100kg, 10km, 30min', max_length=50)),
                ('achieved_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes or context', null=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='exercises.exercise')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-achieved_at'],
            },
        ),
        migrations.CreateModel(
            name='GoalTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_value', models.CharField(help_text='E.g., 70kg, 10km run, 100 pushups', max_length=100)),
                ('current_value', models.CharField(blank=True, max_length=100, null=True)),
                ('starting_weight', models.FloatField(blank=True, help_text='Weight at start of goal tracking', null=True)),
                ('ending_weight', models.FloatField(blank=True, help_text='Weight at achievement or end', null=True)),
                ('progress_percent', models.DecimalField(decimal_places=2, default=0.0, help_text='Progress towards goal (%)', max_digits=5)),
                ('notes', models.TextField(blank=True, help_text='Additional notes or context', null=True)),
                ('is_achieved', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('achieved_at', models.DateTimeField(blank=True, null=True)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goal_trackings', to='workout_plan.goal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goal_progress', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WeightLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_kg', models.DecimalField(decimal_places=2, help_text='Weight in kilograms', max_digits=5)),
                ('bmi', models.DecimalField(blank=True, decimal_places=2, help_text='Body Mass Index', max_digits=4, null=True)),
                ('body_fat_percent', models.DecimalField(blank=True, decimal_places=2, help_text='Body fat percentage', max_digits=4, null=True)),
                ('logged_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes or context', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weight_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-logged_at'],
            },
        ),
    ]
