# Generated by Django 5.2.6 on 2025-09-30 23:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0001_initial'),
        ('tracking', '0001_initial'),
        ('workout_plan', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='achievement',
            options={'ordering': ['-achieved_at'], 'verbose_name': 'Achievement', 'verbose_name_plural': 'Achievements'},
        ),
        migrations.AlterModelOptions(
            name='goaltracking',
            options={'verbose_name': 'Goal Tracking', 'verbose_name_plural': 'Goal Trackings'},
        ),
        migrations.AlterModelOptions(
            name='weightlog',
            options={'ordering': ['-logged_at'], 'verbose_name': 'Weight Log', 'verbose_name_plural': 'Weight Logs'},
        ),
        migrations.AlterField(
            model_name='achievement',
            name='achieved_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Achieved At'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='description',
            field=models.CharField(help_text="E.g., 'Bench pressed 100kg for 5 reps'", max_length=255, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='exercises.exercise', verbose_name='Exercise'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes or context', null=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='value',
            field=models.CharField(help_text='E.g., 100kg, 10km, 30min', max_length=50, verbose_name='Value'),
        ),
        migrations.AlterField(
            model_name='goaltracking',
            name='achieved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Achieved At'),
        ),
        migrations.AlterField(
            model_name='goaltracking',
            name='current_value',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Current Value'),
        ),
        migrations.AlterField(
            model_name='goaltracking',
            name='ending_weight',
            field=models.FloatField(blank=True, help_text='Weight at achievement or end', null=True, verbose_name='Ending Weight'),
        ),
        migrations.AlterField(
            model_name='goaltracking',
            name='goal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goal_trackings', to='workout_plan.goal', verbose_name='Goal'),
        ),
        migrations.AlterField(
            model_name='goaltracking',
            name='is_achieved',
            field=models.BooleanField(default=False, verbose_name='Is Achieved'),
        ),
        migrations.AlterField(
            model_name='goaltracking',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes or context', null=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='goaltracking',
            name='progress_percent',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Progress towards goal (%)', max_digits=5, verbose_name='Progress (%)'),
        ),
        migrations.AlterField(
            model_name='goaltracking',
            name='started_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Started At'),
        ),
        migrations.AlterField(
            model_name='goaltracking',
            name='starting_weight',
            field=models.FloatField(blank=True, help_text='Weight at start of goal tracking', null=True, verbose_name='Starting Weight'),
        ),
        migrations.AlterField(
            model_name='goaltracking',
            name='target_value',
            field=models.CharField(help_text='E.g., 70kg, 10km run, 100 pushups', max_length=100, verbose_name='Target Value'),
        ),
        migrations.AlterField(
            model_name='goaltracking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goal_progress', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='weightlog',
            name='bmi',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Body Mass Index', max_digits=4, null=True, verbose_name='BMI'),
        ),
        migrations.AlterField(
            model_name='weightlog',
            name='body_fat_percent',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Body fat percentage', max_digits=4, null=True, verbose_name='Body Fat (%)'),
        ),
        migrations.AlterField(
            model_name='weightlog',
            name='logged_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Logged At'),
        ),
        migrations.AlterField(
            model_name='weightlog',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes or context', null=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='weightlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weight_logs', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='weightlog',
            name='weight_kg',
            field=models.DecimalField(decimal_places=2, help_text='Weight in kilograms', max_digits=5, verbose_name='Weight (kg)'),
        ),
    ]
